# Copyright 2024-2025 The Robbyant Team Authors. All rights reserved.
"""Global shared configuration module.

Defines config items common to all tasks (demo / libero / franka / robotwin). Each task
config file merges these items via ``xxx_cfg.update(va_shared_cfg)`` and then appends its
task-specific hyperparameters, keeping service address, dtype, patch size, etc. globally
consistent.
"""
import torch
from easydict import EasyDict

# Shared config object (EasyDict enables attribute-style access, e.g. cfg.host)
va_shared_cfg = EasyDict()

# Listen address of the inference websocket server; 0.0.0.0 means all NICs
va_shared_cfg.host = '0.0.0.0'
# Listen port of the inference websocket server; eval clients / real robots connect via host:port
va_shared_cfg.port = 29536

# Model parameter and compute dtype; bf16 halves memory with a wide dynamic range, used for both training and inference
va_shared_cfg.param_dtype = torch.bfloat16
# Output root directory: checkpoints, logs, demo.mp4 generated by i2va, etc. are all written here
va_shared_cfg.save_root = './train_out'

# DiT patchify size (T, H, W): no temporal downsampling, 2x2 spatial patches;
# determines video tokens per latent frame = (H/2)*(W/2), affecting the attention window and KV cache size
va_shared_cfg.patch_size = (1, 2, 2)

# Whether to enable offload: when True, VAE / text encoder live on CPU and are moved to GPU only
# during encode/decode, greatly reducing inference memory (~18G is enough for i2va);
# keep False for training (resident on GPU is faster)
va_shared_cfg.enable_offload = False